# CDSs from full-length transcripts
proteins_shortlist:
  bjap_mm  : /ebio/abt2_projects/ag-swart-karyocode/nb/shortlist-seqs/transcript_shortlist_pep.bjap_mm.fasta
  bsp_mk   : /ebio/abt2_projects/ag-swart-karyocode/nb/shortlist-seqs/transcript_shortlist_pep.bsp_mk.fasta
  cmag_mm  : /ebio/abt2_projects/ag-swart-karyocode/nb/shortlist-seqs/transcript_shortlist_pep.cmag_mm.fasta
  gacu_yy  : /ebio/abt2_projects/ag-swart-karyocode/nb/shortlist-seqs/transcript_shortlist_pep.gacu_yy.fasta
  lstr2_yy : /ebio/abt2_projects/ag-swart-karyocode/nb/shortlist-seqs/transcript_shortlist_pep.lstr2_yy.fasta
  lstr_yy  : /ebio/abt2_projects/ag-swart-karyocode/nb/shortlist-seqs/transcript_shortlist_pep.lstr_yy.fasta
  lx13_yy  : /ebio/abt2_projects/ag-swart-karyocode/nb/shortlist-seqs/transcript_shortlist_pep.lx13_yy.fasta
  pard_mm  : /ebio/abt2_projects/ag-swart-karyocode/nb/shortlist-seqs/transcript_shortlist_pep.pard_mm.fasta
  sa331_kh : /ebio/abt2_projects/ag-swart-karyocode/nb/shortlist-seqs/transcript_shortlist_pep.sa331_kh.fasta
  sa332_kh : /ebio/abt2_projects/ag-swart-karyocode/nb/shortlist-seqs/transcript_shortlist_pep.sa332_kh.fasta
  spol_upp : /ebio/abt2_projects/ag-swart-karyocode/nb/shortlist-seqs/transcript_shortlist_pep.spol_upp.fasta
  trac_yy  : /ebio/abt2_projects/ag-swart-karyocode/nb/shortlist-seqs/transcript_shortlist_pep.trac_yy.fasta
  N10 : /ebio/abt2_projects/ag-swart-karyocode/nb/shortlist-seqs/transcript_shortlist_pep.N10.fasta
  N26 : /ebio/abt2_projects/ag-swart-karyocode/nb/shortlist-seqs/transcript_shortlist_pep.N26.fasta
  N27 : /ebio/abt2_projects/ag-swart-karyocode/nb/shortlist-seqs/transcript_shortlist_pep.N27.fasta
  N34 : /ebio/abt2_projects/ag-swart-karyocode/nb/shortlist-seqs/transcript_shortlist_pep.N34.fasta
  N38 : /ebio/abt2_projects/ag-swart-karyocode/nb/shortlist-seqs/transcript_shortlist_pep.N38.fasta
  N4  : /ebio/abt2_projects/ag-swart-karyocode/nb/shortlist-seqs/transcript_shortlist_pep.N4.fasta
  N44 : /ebio/abt2_projects/ag-swart-karyocode/nb/shortlist-seqs/transcript_shortlist_pep.N44.fasta
  N5  : /ebio/abt2_projects/ag-swart-karyocode/nb/shortlist-seqs/transcript_shortlist_pep.N5.fasta
  N70 : /ebio/abt2_projects/ag-swart-karyocode/nb/shortlist-seqs/transcript_shortlist_pep.N70.fasta
  N72 : /ebio/abt2_projects/ag-swart-karyocode/nb/shortlist-seqs/transcript_shortlist_pep.N72.fasta
  ref_bsto : /ebio/abt2_projects/ag-swart-karyocode/analysis/busco/db/proteomes/Blepharisma_stoltei.2021.faa
  ref_evan : /ebio/abt2_projects/ag-swart-karyocode/analysis/busco/db/proteomes/Euplotes_vannus.2018-03.faa
  ref_imul : /ebio/abt2_projects/ag-swart-karyocode/analysis/busco/db/proteomes/Ichthyophthirius_multifiliis.img1_0407.faa
  ref_lmag : /ebio/abt2_projects/ag-swart-karyocode/analysis/busco/db/proteomes/Loxodes_magnus.MAC_falcon.faa
  ref_otri : /ebio/abt2_projects/ag-swart-karyocode/analysis/busco/db/proteomes/Oxytricha_trifallax.2020.faa
  ref_pcau : /ebio/abt2_projects/ag-swart-karyocode/analysis/busco/db/proteomes/Paramecium_caudatum_43c3d.v2.faa
  ref_ptet : /ebio/abt2_projects/ag-swart-karyocode/analysis/busco/db/proteomes/Paramecium_tetraurelia_51.v2.faa
  ref_pmar : /ebio/abt2_projects/ag-swart-karyocode/analysis/busco/db/proteomes/Perkinsus_marinus_ATCC50983.JCVI_PMG_1.faa
  ref_pper : /ebio/abt2_projects/ag-swart-karyocode/analysis/busco/db/proteomes/Pseudocohnilembus_persalinus.1_ASM144751v1.faa
  ref_sceo : /ebio/abt2_projects/ag-swart-karyocode/analysis/busco/db/proteomes/Stentor_coeruleus.2017-11.faa
  ref_slem : /ebio/abt2_projects/ag-swart-karyocode/analysis/busco/db/proteomes/Stylonychia_lemnae.2017-11.faa
  ref_tbor : /ebio/abt2_projects/ag-swart-karyocode/analysis/busco/db/proteomes/Tetrahymena_borealis.2012-10.faa
  ref_tell : /ebio/abt2_projects/ag-swart-karyocode/analysis/busco/db/proteomes/Tetrahymena_elliotti.2012-10.faa
  ref_tmal : /ebio/abt2_projects/ag-swart-karyocode/analysis/busco/db/proteomes/Tetrahymena_malaccensis.2012-10.faa
  ref_tthe : /ebio/abt2_projects/ag-swart-karyocode/analysis/busco/db/proteomes/Tetrahymena_thermophila.2020.faa
