# CDSs from full-length transcripts
proteins_shortlist:
  N10 : /ebio/abt2_projects/ag-swart-karyocode/nb/shortlist-seqs/transcript_shortlist_trans.N10.fasta
  N26 : /ebio/abt2_projects/ag-swart-karyocode/nb/shortlist-seqs/transcript_shortlist_trans.N26.fasta
  N27 : /ebio/abt2_projects/ag-swart-karyocode/nb/shortlist-seqs/transcript_shortlist_trans.N27.fasta
  N34 : /ebio/abt2_projects/ag-swart-karyocode/nb/shortlist-seqs/transcript_shortlist_trans.N34.fasta
  N38 : /ebio/abt2_projects/ag-swart-karyocode/nb/shortlist-seqs/transcript_shortlist_trans.N38.fasta
  N39 : /ebio/abt2_projects/ag-swart-karyocode/nb/shortlist-seqs/transcript_shortlist_trans.N39.fasta
  N4  : /ebio/abt2_projects/ag-swart-karyocode/nb/shortlist-seqs/transcript_shortlist_trans.N4.fasta
  N44 : /ebio/abt2_projects/ag-swart-karyocode/nb/shortlist-seqs/transcript_shortlist_trans.N44.fasta
  N5  : /ebio/abt2_projects/ag-swart-karyocode/nb/shortlist-seqs/transcript_shortlist_trans.N5.fasta
  N6  : /ebio/abt2_projects/ag-swart-karyocode/nb/shortlist-seqs/transcript_shortlist_trans.N6.fasta
  N70 : /ebio/abt2_projects/ag-swart-karyocode/nb/shortlist-seqs/transcript_shortlist_trans.N70.fasta
  N72 : /ebio/abt2_projects/ag-swart-karyocode/nb/shortlist-seqs/transcript_shortlist_trans.N72.fasta
